# .travis.yml installing miniconda3 on two different distributions and recreating environment from pre-existing environment.yml. 
# The environment.yml used here has been created by using this command: conda env export --from-history > environment.yml 




language: bash

matrix:
  include:

    - os: linux
      dist: xenial

    - os: osx
      # macos 10.15.5
      osx_image: xcode12

# Install miniconda
before_install: 
  - "if [ \"$TRAVIS_OS_NAME\" = \"linux\" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi"
  - "if [ \"$TRAVIS_OS_NAME\" = \"osx\" ]; then wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi"
  - "bash miniconda.sh -b -p $HOME/miniconda"
  - "source \"$HOME/miniconda/etc/profile.d/conda.sh\""
  #- "hash -r"

# configure conda environment
install:
  - "conda config --set always_yes yes --set changeps1 no"
  - "conda update -q conda"
  - "conda env create -n reproduce-me-env -f environment.yml"
  - "conda activate reproduce-me-env"
  - "conda info -a"
  - "conda list" 

script:
  - pytest execute_me_test.py