# template based on https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
#  https://docs.travis-ci.com/user/reference/osx
#  https://docs.travis-ci.com/user/languages/python/
language: python

jobs:
  include:
    - os: linux
      dist: trusty

    - os: osx
      # macos 10.13
      osx_image: xcode10.1

    - os: osx
      # macos 10.14.6
      osx_image: xcode11.3

    - os: osx
      # macos 10.15.5
      osx_image: xcode12

python:

  - "3.6"

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create --yes --name reproduce-me python=$TRAVIS_PYTHON_VERSION
  - source activate build-environment
  - conda install --yes numpy pandas scipy

  script:
  # Your test script goes here
  - cd src/tests && pytest .