language: python

matrix:
  include:

    # Here you can add or remove specific builds, and Python versions. You
    # should currently be able to use Python 2.6, 2.7, or 3.3 or later. The
    # NUMPY and SCIPY versions are set here as an example, but you can
    # add/remove environment variables, and use them below during the install.
    - os: osx
      env: TRAVIS_PYTHON_VERSION=3.5
    - os: osx
      env: TRAVIS_PYTHON_VERSION=3.8 

before_install:

  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install foo; else brew install bar; fi
  # Miniconda Linux

  #- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  #- chmod +x miniconda.sh
  #- ./miniconda.sh -b
  #- export PATH=/home/travis/miniconda/bin:$PATH
  #- conda update --yes conda

  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes -q conda
  - conda config --set anaconda_upload no
  - conda config --add channels conda-forge
  - conda info -a

install:
  - conda create --yes --name build-environment python=$TRAVIS_PYTHON_VERSION
  - source activate build-environment
  - conda install --yes numpy pandas scipy
  - conda build --python $TRAVIS_PYTHON_VERSION 
script:

  - py.test  # will run all tests in the package
